# Generated by Django 4.2 on 2023-04-26 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("qabot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="data",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.TextField()),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_sender",
                        to="qabot.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat_history",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chat_history",
                to="qabot.chathistory",
            ),
        ),
    ]
