# Generated by Django 4.2.1 on 2023-05-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qabot", "0003_alter_chathistory_sender_alter_document_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="chat_history",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_history",
                to="qabot.chathistory",
            ),
        ),
    ]
